# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName(_fromUtf8("Dashboard"))
        Dashboard.resize(1888, 917)
        self.centralwidget = QtGui.QWidget(Dashboard)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 9, -1, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 5, 2, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 6, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        self.videoPlayer.setMinimumSize(QtCore.QSize(600, 390))
        self.videoPlayer.setMaximumSize(QtCore.QSize(600, 390))
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        self.gridLayout_2.addWidget(self.videoPlayer, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.file_browser_button = QtGui.QPushButton(self.groupBox)
        self.file_browser_button.setGeometry(QtCore.QRect(240, 80, 121, 21))
        self.file_browser_button.setObjectName(_fromUtf8("file_browser_button"))
        self.current_file_display = QtGui.QTextBrowser(self.groupBox)
        self.current_file_display.setGeometry(QtCore.QRect(10, 20, 221, 31))
        self.current_file_display.setObjectName(_fromUtf8("current_file_display"))
        self.date_created = QtGui.QTextBrowser(self.groupBox)
        self.date_created.setGeometry(QtCore.QRect(240, 20, 121, 31))
        self.date_created.setObjectName(_fromUtf8("date_created"))
        self.data_file_display = QtGui.QTextBrowser(self.groupBox)
        self.data_file_display.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.data_file_display.setObjectName(_fromUtf8("data_file_display"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 0, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 120, 361, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.fast_backward = QtGui.QPushButton(self.layoutWidget)
        self.fast_backward.setObjectName(_fromUtf8("fast_backward"))
        self.gridLayout_5.addWidget(self.fast_backward, 0, 1, 1, 1)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.layoutWidget)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.gridLayout_5.addWidget(self.volumeSlider, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.start_video = QtGui.QPushButton(self.layoutWidget)
        self.start_video.setStyleSheet(_fromUtf8(""))
        self.start_video.setObjectName(_fromUtf8("start_video"))
        self.gridLayout_5.addWidget(self.start_video, 0, 2, 1, 1)
        self.fast_forward = QtGui.QPushButton(self.layoutWidget)
        self.fast_forward.setObjectName(_fromUtf8("fast_forward"))
        self.gridLayout_5.addWidget(self.fast_forward, 0, 3, 1, 1)
        self.start_point = QtGui.QTextBrowser(self.groupBox)
        self.start_point.setGeometry(QtCore.QRect(10, 190, 181, 51))
        self.start_point.setObjectName(_fromUtf8("start_point"))
        self.end_point = QtGui.QTextBrowser(self.groupBox)
        self.end_point.setGeometry(QtCore.QRect(10, 260, 181, 51))
        self.end_point.setObjectName(_fromUtf8("end_point"))
        self.begin_point_rb = QtGui.QRadioButton(self.groupBox)
        self.begin_point_rb.setGeometry(QtCore.QRect(10, 170, 101, 21))
        self.begin_point_rb.setObjectName(_fromUtf8("begin_point_rb"))
        self.end_point_rb = QtGui.QRadioButton(self.groupBox)
        self.end_point_rb.setGeometry(QtCore.QRect(10, 240, 101, 21))
        self.end_point_rb.setObjectName(_fromUtf8("end_point_rb"))
        self.tags = QtGui.QComboBox(self.groupBox)
        self.tags.setGeometry(QtCore.QRect(200, 200, 121, 31))
        self.tags.setObjectName(_fromUtf8("tags"))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tags.addItem(_fromUtf8(""))
        self.tag_data = QtGui.QPushButton(self.groupBox)
        self.tag_data.setGeometry(QtCore.QRect(200, 240, 121, 31))
        self.tag_data.setObjectName(_fromUtf8("tag_data"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lcd_video_time = QtGui.QLCDNumber(self.groupBox)
        self.lcd_video_time.setGeometry(QtCore.QRect(0, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lcd_video_time.setFont(font)
        self.lcd_video_time.setDigitCount(9)
        self.lcd_video_time.setObjectName(_fromUtf8("lcd_video_time"))
        self.lcd_data_time = QtGui.QLCDNumber(self.groupBox)
        self.lcd_data_time.setGeometry(QtCore.QRect(160, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lcd_data_time.setFont(font)
        self.lcd_data_time.setDigitCount(9)
        self.lcd_data_time.setObjectName(_fromUtf8("lcd_data_time"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 320, 71, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 320, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(370, 20, 321, 301))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(230, 280, 81, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.show_events = QtGui.QCheckBox(self.groupBox)
        self.show_events.setGeometry(QtCore.QRect(230, 300, 91, 21))
        self.show_events.setObjectName(_fromUtf8("show_events"))
        self.curr_event = QtGui.QTextBrowser(self.groupBox)
        self.curr_event.setGeometry(QtCore.QRect(370, 340, 321, 31))
        self.curr_event.setObjectName(_fromUtf8("curr_event"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(370, 320, 111, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(50, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(50, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 3, 1, 1)
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        self.seekSlider.setMaximumSize(QtCore.QSize(16777215, 25))
        self.seekSlider.setIconVisible(True)
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.gridLayout_8.addWidget(self.seekSlider, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 9, 1)
        Dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1888, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Dashboard.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Dashboard)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        Dashboard.setWindowTitle(_translate("Dashboard", "Dashboard", None))
        self.file_browser_button.setText(_translate("Dashboard", "Choose a file", None))
        self.label_4.setText(_translate("Dashboard", "Date created:", None))
        self.label_6.setText(_translate("Dashboard", "Current video file:", None))
        self.fast_backward.setText(_translate("Dashboard", "<<", None))
        self.start_video.setText(_translate("Dashboard", "Start/Pause", None))
        self.fast_forward.setText(_translate("Dashboard", ">>", None))
        self.begin_point_rb.setText(_translate("Dashboard", "Begin point:", None))
        self.end_point_rb.setText(_translate("Dashboard", "End point:", None))
        self.tags.setItemText(0, _translate("Dashboard", "skret w prawo", None))
        self.tags.setItemText(1, _translate("Dashboard", "wartosc referencyjna", None))
        self.tags.setItemText(2, _translate("Dashboard", "skret w lewo", None))
        self.tags.setItemText(3, _translate("Dashboard", "zmiana pasa na lewy", None))
        self.tags.setItemText(4, _translate("Dashboard", "zmiana pasa na prawy", None))
        self.tags.setItemText(5, _translate("Dashboard", "indle", None))
        self.tags.setItemText(6, _translate("Dashboard", "hamowanie", None))
        self.tags.setItemText(7, _translate("Dashboard", "przyspieszanie na swiatlach", None))
        self.tags.setItemText(8, _translate("Dashboard", "zatrzymanie na swiatlach", None))
        self.tag_data.setText(_translate("Dashboard", "Tag data", None))
        self.label.setText(_translate("Dashboard", "Current data file:", None))
        self.label_2.setText(_translate("Dashboard", "Video time:", None))
        self.label_3.setText(_translate("Dashboard", "Plotted data time:", None))
        self.checkBox.setText(_translate("Dashboard", "show speed", None))
        self.show_events.setText(_translate("Dashboard", "show events", None))
        self.label_5.setText(_translate("Dashboard", "Current event", None))

from PyQt4 import phonon
